### ISSUE TITLE
Is there a way to enable dynamic GPU-memory allocaction using standard classes from sklearn and keras?

### ISSUE THREAD

**Issue by henningsway** [capkuro/Keras-GridSearchCV#2]
Hey there,

I am currently using GridSearch and the Keras-Wrapper for sklearn to optimize my Pipeline via `Sklearn.GridSeachCV`. I took a look at your code and some discussions on on stackoverflow: https://stackoverflow.com/questions/34199233/how-to-prevent-tensorflow-from-allocating-the-totality-of-a-gpu-memory/48677030#48677030

To me, it seems, that the proposed workarounds (e.g. https://github.com/keras-team/keras/issues/4161#issuecomment-366031228) are not working for my use case, but I do not feel comfortable to tweak `GridSeachCV` or `KerasClassifier`.

Do you have suggestions how to get this to work, without altering these classes? :)

**Comment by capkuro** [comment]
Hi @henningsway,

My main supposition is that the GPU memory is not freed after each iteration of the model evaluation (that's why I force the use of the keras backend `clear_session()` method). Unless there is a way to trigger the cleaning of the session (via keras or tensorflow), I can not think of a way of doing this without tweaking the `sklearn` related classes.

Maybe, you can use another way to do hyperparameter optimization via [hyperas](https://github.com/maxpumperla/hyperas), [talos](https://github.com/autonomio/talos), or [optuna](https://github.com/pfnet/optuna) (obviously, only if it is compatible with your pipeline). 

I hope this answer helps you with your pipeline.

**Comment by henningsway** [comment]
Thank you so much for your ideas. Let me give this some thought and possibly get back to you. :)
